spring:
  application:
    name: milestone-service
  #zipkin:
    #base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
server:
  port: 8001
eureka:
  instance:
    hostname: localhost
    secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/